### ISSUE TITLE
Missing password on user credentials

### ISSUE THREAD

**Issue by rtrive** [keycloak/keycloak-operator#409]
### Describe the bug

When a new user is created, the operator create the relative secret without random password. 
The documentation said that also a random password is created but unfortunately is not like this. 

### Version

15.0.2

### Expected behavior

Secret will have both username and password not only username

### Actual behavior

Secret is created with only username

### How to Reproduce?

Create a user through Keycloak user example (without credentials)

**Comment by bsctl** [comment]
Same issue here.

A keycloak user according to doc:

```yaml
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  labels:
    app: keycloak
  name: cloudgaap-cli
  namespace: keycloak
spec:
  realmSelector:
    matchLabels:
      app: keycloak
  user:
    email: cloudgaap-cli@example.com
    enabled: true
    username: cloudgaap-cli
status:
  message: secrets "credential-cloudgaap-cloudgaap-cli-keycloak" already exists
  phase: reconciled
```

Secret

```yaml
apiVersion: v1
data:
  username: Y2xvdWRnYWFwLWNsaQ==
kind: Secret
metadata:
  namespace: keycloak
  ownerReferences:
  - apiVersion: keycloak.org/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: KeycloakUser
    name: cloudgaap-cli
type: Opaque
```

**Comment by jonathanvila** [comment]
Hi @bsctl @rtrive 
Thank you for reporting this issue , your feedback helps us a lot.

I've been investigating the issue and these are my findings : 
* The operator won't create a default password for a KeycloakUser
* It is Keycloak internally who will assign a default password to that user upon the Keycloak Operator request on the KeycloakUser CR reconcilliation
* In the above case that password created in Keycloak won't be added to the Secret created by the Operator
* You can assign a password to that user if you specify `credentials` in the KeycloakUser spec : 
```yaml
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: example-realm-user-with-creds
  labels:
    app: sso
spec:
  user:
    username: "creds_user"
    firstName: "Creds"
    lastName: "User"
    email: "creds_user@redhat.com"
    enabled: True
    emailVerified: False
    credentials:
      - type: "password"
        value: "12345"
    realmRoles:
      - "offline_access"
    clientRoles:
      account:
        - "manage-account"
      realm-management:
        - "manage-users"
  realmSelector:
    matchLabels:
      app: sso
```
* Documentation is not accurate enough to explain this details and can lead to confusion. We'll create a PR to solve this.

Hope this can help you on the issue. I will close it as not a bug, but feel free to reopen it if you can provide more information.
