### ISSUE TITLE
Cannot manage authorization settings (scopes, resources, policies, permissions) through KeycloakClient CRD

### ISSUE THREAD

**Issue by krlm** [keycloak/keycloak-operator#410]
### Describe the bug

I can only define scopes, resources, policies using `KeycloakClient` CRD during creation of given client. When I change existing definition by adding new (or removing/modifying existing) scopes/policies/resources/permissions then changes aren't reflected until i drop and recreate the client. Is it expected behaviour?  

### Version

15.0.2

### Expected behavior

I'd expect that applied change of defined scopes/resources/policies/permissions would be reflected in a given client Keycloak configuration.

### Actual behavior

Changes of authorization settings (policies/permissions/etc) applied to existing `KeycloakClient` definition are ignored until the client is dropped and then re-created. 

### How to Reproduce?

Create some basic client with some scopes and resources: i.e. 

```yaml
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: api
  labels:
    app: sso
spec:
  realmSelector:
     matchLabels:
      app: sso
  client:
    clientId: api
    secret: DEADBEAF
    baseUrl: http://api.example
    clientAuthenticatorType: client-secret
    protocol: openid-connect
    serviceAccountsEnabled: true
    authorizationServicesEnabled: true
    authorizationSettings:
      scopes:
        - name: "Scope"      
          displayName: "Scope"
      resources:
        - name: "Resource"
          displayName: "Resource"
          uris:
            - "/RESOURCE/*"
          scopes:
            - name: "resource.scope"
```
create that client:
```
kubectl apply -f client.yaml
```
and then try to modify or extend scopes or resources, i.e.

```yaml
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: api
  labels:
    app: sso
spec:
  realmSelector:
     matchLabels:
      app: sso
  client:
    clientId: api
    secret: DEADBEAF
    baseUrl: http://api.example
    clientAuthenticatorType: client-secret
    protocol: openid-connect
    serviceAccountsEnabled: true
    authorizationServicesEnabled: true
    authorizationSettings:
      scopes:
        - name: "Scope"      
          displayName: "Scope"
        - name: "New Scope"      
          displayName: "New Scope"
      resources:
        - name: "Resource with new name"
          displayName: "Resource"
          uris:
            - "/RESOURCE/*"
          scopes:
            - name: "resource.scope"
```
and apply changes: 
```
kubectl apply -f client.yaml
```
Changes aren't reflected until I recreate the client.
