### ISSUE TITLE
Allow to specify secrets labels and annotations from keycloakclient

### ISSUE THREAD

**Issue by sathieu** [keycloak/keycloak-operator#413]
### Description

We have several applications in different namespaces needing SSO. Those can take the oidc client secret as input from a k8s secret in the same namespace as the application.

I first tried to expand the keycloak-operator to look for keycloakclients in other namespaces (https://github.com/keycloak/keycloak-operator/pull/398), this was rejected because of incomplete implementation.

My next try is to copy the created secret using kubed. But kubed only copy secrets having a label (for example `kubed.appscode.com/sync: "kubernetes.io/metadata.name=grafana"`, ref: https://appscode.com/products/kubed/v0.13.0-beta.0/guides/config-syncer/intra-cluster/).

I'm proposing to extend the CRD. For example:

```yaml
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  namespace: keycloak
  name: grafana-oidc-client-secret
  labels:
    app: sso
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  realmSelector:
    matchLabels:
      app: sso
  client:
    clientId: grafana
    clientAuthenticatorType: client-secret
    standardFlowEnabled: true
    redirectUris:
    - https://grafana.example.org/*
    webOrigins:
    - '+' # redirectUris
    defaultClientScopes:
    - email
    - profile
    # V V V V V V V V V V V here V V V V V V V V V V V
    secretTemplate:
      metadata:
        labels:
          kubed.appscode.com/sync: "kubernetes.io/metadata.name=grafana"
    # Λ Λ Λ Λ Λ Λ Λ Λ Λ Λ Λ here Λ Λ Λ Λ Λ Λ Λ Λ Λ Λ Λ
``` 

The code changes are around:

https://github.com/keycloak/keycloak-operator/blob/77d126113104d45e29057f5c9e30c54f1a482763/pkg/model/client_secret.go#L13-L26

See also my WIP Ansible playbooks: https://gitlab.com/kubitus-project/kubitus-installer/-/merge_requests/364

**Comment by sathieu** [comment]
@vmuzikar Could you please review my proposal? We can start implementing it once you validate the proposed CRD schema.

**Comment by tomhuang12** [comment]
I would like this feature as well.

**Comment by tomhuang12** [comment]
An alternative method until the PR is merged is using Kyverno to add labels: https://kyverno.io/policies/other/add_labels/add_labels/

**Comment by andreaTP** [comment]
@tomhuang12 would you like to contribute to this feature?
Or, would you mind quickly summarizing how to use "Kyverno" as a workaround?
Thanks in advance!

**Comment by tomhuang12** [comment]
The policy looks something like this:
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-keycloak-client-secret-kubed-annotations-example
spec:
  rules:
  - name: add-annotations
    match:
      any:
      - resources:
          kinds:
          - Secret
          namespaces:
          - keycloak
          names:
          - keycloak-client-secret-example
    mutate:
      patchStrategicMerge:
        metadata:
          annotations:
            kubed.appscode.com/sync: "kubernetes.io/metadata.name=example"
```
