### ISSUE TITLE
Doesn't upgrade images and probe just fails without any error

### ISSUE THREAD

**Issue by titansmc** [keycloak/keycloak-operator#430]
### Describe the bug

The operator logs look fine:
```
s","controller":"keycloakbackup-controller","worker count":1}
{"level":"info","ts":1640102636.31718,"logger":"controller_keycloakbackup","msg":"Reconciling KeycloakBackup","Request.Namespace":"keycloak-operator","Request.Name":"keycloak-minio-backup-scheduler"}
{"level":"info","ts":1640102638.7181783,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"keycloakuser-controller"}
{"level":"info","ts":1640102642.6195655,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"keycloakuser-controller","worker count":1}
I1221 16:04:05.216134       1 request.go:655] Throttling request took 2.498708727s, request: GET:https://10.133.0.1:443/apis/batch/v1beta1?timeout=32s
{"level":"info","ts":1640102647.3250031,"logger":"action_runner","msg":"(    0)    SUCCESS Update Keycloak admin secret"}
{"level":"info","ts":1640102647.3295093,"logger":"action_runner","msg":"(    1)    SUCCESS Update Postgresql KeycloakService"}
{"level":"info","ts":1640102647.3330376,"logger":"action_runner","msg":"(    2)    SUCCESS Update keycloak Service"}
{"level":"info","ts":1640102647.3362212,"logger":"action_runner","msg":"(    3)    SUCCESS Update keycloak Discovery Service"}
{"level":"info","ts":1640102647.3464978,"logger":"action_runner","msg":"(    4)    SUCCESS Update Keycloak Deployment (StatefulSet)"}
{"level":"info","ts":1640102647.3492367,"logger":"action_runner","msg":"(    5)    SUCCESS Update Keycloak Ingress"}
{"level":"info","ts":1640102647.3549726,"logger":"controller_keycloak","msg":"desired cluster state met"}
{"level":"info","ts":1640102647.6260815,"logger":"controller_keycloakbackup","msg":"Reconciling KeycloakBackup","Request.Namespace":"keycloak-operator","Request.Name":"keycloak-minio-backup-scheduler"}
{"level":"info","ts":1640102652.631358,"logger":"controller_keycloakbackup","msg":"Reconciling KeycloakBackup","Request.Namespace":"keycloak-operator","Request.Name":"keycloak-minio-backup-scheduler"}
I1221 16:04:15.258599       1 request.go:655] Throttling request took 3.598538261s, request: GET:https://10.133.0.1:443/apis/flowcontrol.apiserver.k8s.io/v1beta1?timeout=32s
{"level":"info","ts":1640102657.6372457,"logger":"controller_keycloakbackup","msg":"Reconciling KeycloakBackup","Request.Namespace":"keycloak-operator","Request.Name":"keycloak-minio-backup-scheduler"}
{"level":"info","ts":1640102662.6418972,"logger":"controller_keycloakbackup","msg":"Reconciling KeycloakBackup","Request.Namespace":"keycloak-operator","Request.Name":"keycloak-minio-backup-scheduler"}
I1221 16:04:25.308378       1 request.go:655] Throttling request took 1.948071215s, request: GET:https://10.133.0.1:443/apis/velero.io/v1?timeout=32s
{"level":"info","ts":1640102667.6500669,"logger":"controller_keycloakbackup","msg":"Reconciling KeycloakBackup","Request.Namespace":"keycloak-operator","Request.Name":"keycloak-minio-backup-scheduler"}

```

but the keycloak is not being updated like defined in the instance:
```
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak-test
  labels:
    app: sso
  namespace: keycloak-operator
spec:
  instances: 1
  #extensions:
  #- https://sourcecode.domain.com/sysadmin-public/keycloack-theme/-/raw/master/theme.jar
  migration:
    strategy: recreate
    backups:
      enabled: True
  externalAccess:
    enabled: true
    host: "auth-test.ktest.domain.com"
  externalDatabase:
    enabled: true
  keycloakDeploymentSpec:
    experimental:
      env:
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: RELATED_IMAGE_KEYCLOAK
          value: "quay.io/keycloak/keycloak:16.1.0"
        - name: RELATED_IMAGE_KEYCLOAK_INIT_CONTAINER
          value: "quay.io/keycloak/keycloak-init-container:16.1.0"

```

### Version

16.1.0

### Expected behavior

update the deployment and probe working

### Actual behavior

keucloak is down:
```
  Normal   Pulling    21m                 kubelet            Pulling image "quay.io/keycloak/keycloak-init-container:master"
  Normal   Pulled     21m                 kubelet            Successfully pulled image "quay.io/keycloak/keycloak-init-container:master" in 961.60902ms
  Normal   Created    21m                 kubelet            Created container extensions-init
  Normal   Started    21m                 kubelet            Started container extensions-init
  Normal   Pulled     21m                 kubelet            Container image "quay.io/keycloak/keycloak:16.0.0" already present on machine
  Normal   Created    21m                 kubelet            Created container keycloak
  Normal   Started    21m                 kubelet            Started container keycloak
  Warning  Unhealthy  20m                 kubelet            Liveness probe failed:
  Warning  Unhealthy  40s (x40 over 20m)  kubelet            Readiness probe failed:
```
