### ISSUE TITLE
Setting "enabled: false" for an existing user does not actually disable the user

### ISSUE THREAD

**Issue by chrisbsmith** [keycloak/keycloak-operator#441]
### Describe the bug

I am editing an existing `KeycloakUser` in an attempt to disable the user's access. However, if the user is currently "enabled", setting `enabled: false` or removing the `enabled: true` fails to actually disable the user in Keycloak.

### Version

16.1.0

### Expected behavior

Keycloak should disable the user 

### Actual behavior

Once a user is "enabled", it can never be "disabled".

### How to Reproduce?

Create a new "disabled" user:
```
cat <<EOF | kubectl -n keycloak apply -f -
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: disabled-user
spec:
  user:
    username: "disabled-user"
    firstName: "Disabled"
    lastName: "Test"
    email: "disabled@example.com"
    enabled: False
    emailVerified: False
    credentials:
      - type: "password"
        value: "12345"
    realmRoles:
      - "offline_access"
    clientRoles:
      account:
        - "manage-account"
      realm-management:
        - "manage-users"
  realmSelector:
    matchLabels:
      app: example-keycloak
EOF
```

Open Keycloak and verify that the user is disabled
![image](https://user-images.githubusercontent.com/602099/148264227-d6a22d19-0b5b-4cb0-b76a-dbf2f2eef250.png)

Update the user to enable it.

```
kubectl patch -n keycloak --type=merge keycloakuser disabled-user -p '{"spec":{"user":{"enabled":true}}}'
keycloakuser.keycloak.org/disabled-user patched
```

Open Keycloak and verify the user is enabled
![image](https://user-images.githubusercontent.com/602099/148265664-906d80e2-f2b5-445a-8963-e3218c4c74c3.png)

Attempt to disable the user 
```
kubectl patch -n keycloak --type=merge keycloakuser disabled-user -p '{"spec":{"user":{"enabled":false}}}'
keycloakuser.keycloak.org/disabled-user patched
```

![image](https://user-images.githubusercontent.com/602099/148265754-4fe778ac-cbe9-4c31-b9f2-1fceb880f49d.png)

Keycloak controller logs show it successfully reconciling the user after each patch

```
{"level":"info","ts":1641405498.2681048,"logger":"controller_keycloakuser","msg":"Reconciling KeycloakUser","Request.Namespace":"keycloak","Request.Name":"disabled-user"}
{"level":"info","ts":1641405498.2682028,"logger":"controller_keycloakuser","msg":"found 1 matching realm(s) for user keycloak/disabled-user"}
{"level":"info","ts":1641405498.4976873,"logger":"action_runner","msg":"(    1)    SUCCESS update user disabled-user"}
```

### Anything else?

I followed [these instructions](https://www.keycloak.org/docs/latest/server_installation/index.html#_operator) and installed the Keycloak operator into a minikube cluster using the command line instructions.
