### ISSUE TITLE
The operator cannot specify a Postgres schema

### ISSUE THREAD

**Issue by doctorpangloss** [keycloak/keycloak-operator#450]
### Describe the bug

Expose `DB_SCHEMA` to the operator configuration.

The database configuration should be more normal and specified more flexibly. Consider an immutable CRD specifically for configuration like this.

### Version

16.1.0

### Expected behavior

There should be a way to specify what schema is used by Keycloak.

### Actual behavior

There is not.

### How to Reproduce?

Try to configure a schema other than `public`.

**Comment by andreaTP** [comment]
Hi @doctorpangloss ,

thanks for opening this issue!
Although there is no explicit setting for `DB_SCHEMA` you can set the environment variable using the the `experimental` section of your CR as shown here:
https://github.com/keycloak/keycloak-operator/blob/996c21bca9f1d948e784d4f1ef5caaba5088944e/deploy/examples/keycloak/keycloak-with-experimental-settings.yaml#L41-L50

For your use-case it should look similar to:

```yaml
spec:
  <...>
  keycloakDeploymentSpec:
    experimental:
      env:
        - name: DB_SCHEMA
          value: "<your db schema value>"
```

I am confident this is going to work as it is even tested in the [operator test-suite](https://github.com/keycloak/keycloak-operator/blob/77d126113104d45e29057f5c9e30c54f1a482763/pkg/model/keycloak_deployment_test.go#L75).

Can you please try out this approach and let us know if it solves your issue?
