### ISSUE TITLE
Extension not being downloaded

### ISSUE THREAD

**Issue by eckilein** [keycloak/keycloak-operator#469]
### Describe the bug

Hi,
Similar to a ticket a few days ago(#449), I am facing an issue with deploying my custom theme using the operator.
But for some reason, jar files are not being downloaded on pod start. 
I wait for the pod being ready/running and check the standalone/deployments folder:
```yaml
kubectl -n dev-idm-stack exec -it keycloak-0 -- /bin/bash
bash-4.4$ ls -l opt/jboss/keycloak/standalone/deployments/
total 0
```
I followed the [keycloak-crd](https://github.com/keycloak/keycloak-operator/blob/main/deploy/crds/keycloak.org_keycloaks_crd.yaml#L34) and this is my yaml file:
```yaml
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  labels:
    app: sso
  name: 'keycloak'
  namespace: '{{ k8s_namespace }}'
spec:
  extensions:
  - https://gitlab.com/BeToken/ocp-themes/-/raw/main/theme.jar
  externalAccess:
    enabled: false
  instances: {{ keycloak_replicas }}
  podDisruptionBudget:
    enabled: true
  externalDatabase:
    enabled: true
  keycloakDeploymentSpec:
    experimental:
      args:
        - "-Dkeycloak.profile.feature.scripts=enabled"
        - "-Dkeycloak.profile.feature.upload_scripts=enabled"
      env:
        - name: KEYCLOAK_LOGLEVEL
          value: '{{ inv_idm.keycloak.log_level }}'
        - name: KEYCLOAK_USER
          valueFrom:
            secretKeyRef:
              key: MASTER_USERNAME
              name: '{{ inv_idm.keycloak.k8s_secret_name }}'
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MASTER_PASSWORD
              name: '{{ inv_idm.keycloak.k8s_secret_name }}'
        - name: KEYCLOAK_DEFAULT_THEME
          value: '{{ inv_idm.keycloak.theme }}'
    resources:
      limits:
        cpu: 1500m
        memory: 1500Mi
      requests:
        cpu: 750m
        memory: 750Mi
```

Don't mind some values being in the curly brackets (Deploying everything using ansible).
It also seems to be transferred correctly to k8s:
```yaml
kubectl -n dev-idm-stack describe po keycloak-0 
Name:         keycloak-0
Namespace:    dev-idm-stack
Priority:     0
...
    Ready:          True
    Restart Count:  0
    Environment:
      KEYCLOAK_EXTENSIONS:  https://gitlab.com/BeToken/ocp-themes/-/raw/main/theme.jar
```

When checking the logs there is no indication as well, as far as my understanding of the logs reaches. 

### Version

used main and 16.1.0 specific

### Expected behavior

theme.jar
(and hopefully theme.jar.deployed)
being present in the folder `opt/jboss/keycloak/standalone/deployments/`

### Actual behavior

folder is empty

### How to Reproduce?

Add 
```yaml
spec:
  extensions:
  - https://gitlab.com/BeToken/ocp-themes/-/raw/main/theme.jar
```
and check folder `opt/jboss/keycloak/standalone/deployments/` after keycloak is deployed.

**Comment by eckilein** [comment]
Sorry my reply took so long.

I tried it on a new machine and I get into the (same?) problem.

Here are the logs from the init-container:
```bash
kubectl logs keycloak-0 -c extensions-init 
downloading extension from https://gitlab.com/BeToken/ocp-themes/-/raw/main/theme.jar
'filename'
```

So the file was downloaded, but the content of the folder is still empty.
```bash
kubectl exec -it keycloak-0 -- ls -l opt/jboss/keycloak/standalone/deployments
total 0
```

For completion: Content of the themes folder and the updated deployment.yml
```bash
kubectl exec -it keycloak-0 -- ls
base  keycloak	keycloak.v2  README.txt
```

```yaml
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  labels:
    app: sso
  name: 'keycloak'
  namespace: '{{ k8s_namespace }}'
spec:
  extensions:
  - https://gitlab.com/BeToken/ocp-themes/-/raw/main/theme.jar
  externalAccess:
    enabled: false
  instances: {{ keycloak_replicas }}
  podDisruptionBudget:
    enabled: true
  externalDatabase:
    enabled: true
  keycloakDeploymentSpec:
    experimental:
      args:
        - "-Dkeycloak.profile.feature.scripts=enabled"
        - "-Dkeycloak.profile.feature.upload_scripts=enabled"
      env:
        - name: KEYCLOAK_LOGLEVEL
          value: '{{ inv_idm.keycloak.log_level }}'
        - name: RELATED_IMAGE_KEYCLOAK_INIT_CONTAINER
          value: quay.io/keycloak/keycloak-init-container:16.1.0
        - name: KEYCLOAK_USER
          valueFrom:
            secretKeyRef:
              key: MASTER_USERNAME
              name: '{{ inv_idm.keycloak.k8s_secret_name }}'
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MASTER_PASSWORD
              name: '{{ inv_idm.keycloak.k8s_secret_name }}'
        - name: KEYCLOAK_DEFAULT_THEME
          value: '{{ inv_idm.keycloak.theme }}'
    resources:
      limits:
        cpu: 1500m
        memory: 1500Mi
      requests:
        cpu: 500m
        memory: 750Mi
```
