### ISSUE TITLE
default ImagePullPolicy setting for keycloak manifest (Keycloak Operator) 

### ISSUE THREAD

**Issue by rakeshreddyrg09** [keycloak/keycloak-operator#485]
### Describe the bug

Hey All,
I am using keycloak operator 16.1.0 and it comes with imagepullpolicy as always for keycloak [statefullset ](https://github.com/keycloak/keycloak-operator/blob/main/deploy/crds/keycloak.org_keycloaks_crd.yaml)(keycloak.yaml).
Also it is not defined in the CRD of the keycloak how to specify image pull policy.
Currently, in my case, the keycloak image is present in the private registry and I am pulling from there but, as the imagepullpolicy set as always it is pulling the image every time even if the image is present locally on the node.

Is my understanding correct about this policy. If yes, Can anyone help out if I can modify the policy?

Thank you.

### Version

16.1.0

### Anything else?
Below is my keycloak manifest.

```
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  labels:
      app: test-keycloak
  name: test-keycloak
  namespace: test
spec:
  extensions:
    - ...
  externalDatabase:
    enabled: true
  instances: 1
  externalAccess:
    enabled: false
  keycloakDeploymentSpec:
    experimental:
      env:
        ...
```
