### ISSUE TITLE
Add default NetworkPolicies

### ISSUE THREAD

**Issue by carlosjgp** [keycloak/keycloak-operator#492]
### Description

Add a sensible default NetworkPolicies for the operator to be able to connect with the Keycloacks deployed on CNI secured clusters

### Motivation

Being able to use the operator and things working on a CNI secure cluster out of the box

### Details

This is the network policy I'm using Cilium v1.11.1
```
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: keycloak-operator
spec:
  endpointSelector:
    matchLabels:
      name: keycloak-operator
  egress:
    - toEndpoints:
        - matchLabels:
            component: keycloak
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: keycloak-component
spec:
  endpointSelector:
    matchLabels:
      component: keycloak
  ingress:
    - fromEndpoints:
        - matchLabels:
            name: keycloak-operator
```

a K8s native version of the above is
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: keycloak-operator
spec:
  podSelector:
    matchLabels:
      name: keycloak-operator
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              component: keycloak
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: keycloak-component
spec:
  podSelector:
    matchLabels:
      component: keycloak
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              name: keycloak-operator
```
