### ISSUE TITLE
Readiness and Liveness probes failing on IPv6

### ISSUE THREAD

**Issue by MrHassanMurtaza** [keycloak/keycloak-operator#494]
### Describe the bug

The pod is getting created and keycloak is getting started but due to failing Readiness and Liveliness probes, the keycloak is getting restarted again and again. 

The manifest looks like this:

```
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak
  labels:
    app: sso
spec:
  instances: 1
  keycloakDeploymentSpec:
    experimental:
      serviceAccountName: "keycloak-operator"
      env:
        # to enable LDAP debug, use: -Djavax.net.debug=ssl:keymanager:trustmanager
        - name: JAVA_OPTS
          value: "-Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true -Djboss.bind.address.private=::1 -Djboss.bind.address=::1"
  extensions:
    - https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.5.3/keycloak-metrics-spi-2.5.3.jar
  externalAccess:
    enabled: False
  podDisruptionBudget:
    enabled: False
  # User needs to provision the external database
  externalDatabase:
    enabled: True
```

On further investigation, it seems like the config map created by the operator uses curl and curl expects square brackets around the hostname.
Currently at the following instances:
- https://github.com/keycloak/keycloak-operator/blob/996c21bca9f1d948e784d4f1ef5caaba5088944e/pkg/model/keycloak_probes.go#L13 
- https://github.com/keycloak/keycloak-operator/blob/996c21bca9f1d948e784d4f1ef5caaba5088944e/pkg/model/keycloak_probes.go#L43

The hostname in both instances should look like this: `http://[$(hostname -i)]:8080/auth ` (note the square brackets around hostname) to make it work. Currently, we have manually edited the config map but it doesn't persist. 

### Version

1.21

### Expected behavior

The keycloak instance should get started and pass all the liveliness/readiness checks described in the config map `keycloak-probes`. 

### Actual behavior

The liveliness/readiness checks are failing therefore the keycloak pod is getting killed/restarted again and again.

### How to Reproduce?

Deploy the keycloak on IPv6 enabled cluster where the pods are getting IPv6 addresses from CNI.
