### ISSUE TITLE
Self defined client scopes remove all default client scopes

### ISSUE THREAD

**Issue by manu11th** [keycloak/keycloak-operator#497]
### Describe the bug

A KeycloakRealm CR with `clientScopes` field defined and containing some self defined client scopes creates a realm at keycloak which only contains the self-defined client scopes and NOT the default client scopes like email, profile, address, roles, role_list, etc.

### Version

16.1.0

### Expected behavior

When creating a KeycloakRealm CR with `clientScopes` field defined and containing some self defined client scopes, a realm is created which contains the self-defined client scopes AND the default client scopes like email, profile, roles, address, etc.

### Actual behavior

When creating a KeycloakRealm CR with `clientScopes` field defined and containing some self defined client scopes, a realm is created which only contains the self-defined client scopes and NOT the default client scopes like email, profile, address, roles, role_list, etc.

### How to Reproduce?

Create a realm with no client scopes defined:
```
apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: test-realm
  labels:
    realm: test-realm
spec:
  instanceSelector:
    matchLabels:
      keycloak: keycloak-label
  realm:
    id: "test"
    realm: "test"
    enabled: True
    displayName: "test Realm"
```
Have a look into the keycloak UI and see all the default client scopes like email, address, role, etc.

Now create another realm with client scopes defined:
````
apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: test-realm
  labels:
    realm: test-realm
spec:
  instanceSelector:
    matchLabels:
      keycloak: keycloak-label
  realm:
    realm: "test"
    enabled: True
    displayName: "test Realm"
    clientScopes:
      - name: additional-token-claims
        protocol: openid-connect
        protocolMappers:
          - name: realm-claim-mapper
            protocol: openid-connect
            protocolMapper: oidc-hardcoded-claim-mapper
            config:
              access.token.claim: "true"
              userinfo.token.claim: "true"
              id.token.claim: "true"
              claim.name: test
              claim.value: my-test-value
              jsonType.label: String
```
Have a look into the keycloak UI and compare the client scopes of the two created realms. The first contains all default client scopes, the second one only contains the self defined client scopes.

### Anything else?
