### ISSUE TITLE
Add Annotations to keycloak pod

### ISSUE THREAD

**Issue by bovigny** [keycloak/keycloak-operator#500]
### Description

Add Annotations to keycloak pod

### Motivation

Actually we can only use labels for keycloak pod, unfortunately when you want to use multus annotations are necessary

**Comment by Stefanqn** [comment]
any update on this? We also need it to add metrics annotations to keycloak, e.g.
```yaml
prometheus.io/scrape: "true"
prometheus.io/path: "/auth/realms/master/metrics"
prometheus.io/port: "8080"
prometheus.io/scheme: "http"
```
