### ISSUE TITLE
Not status after deploying kind: Keycloak

### ISSUE THREAD

**Issue by magick93** [keycloak/keycloak-operator#502]
### Describe the bug

I've deployed OLM and the keycloak CRDs. 

However, when I attempt to create a instance of a Keycloak, using the below yaml, it does succeed, but there is never any pod(s) created, or status.

`kubectl get keycloak/example-keycloak -o jsonpath='{.status.ready}' -n testing` returns nothing.

`kubectl get keycloaks --all-namespaces` shows no keycloak pods running.

```
apiVersion: keycloak.org/v1alpha1
        kind: Keycloak
        metadata:
          name: example-keycloak
          namespace: "{{ namespace }}"
          labels:
            app: sso
        spec:
          instances: 1
          extensions:
            - https://github.com/aerogear/keycloak-metrics-spi/releases/download/1.0.4/keycloak-metrics-spi-1.0.4.jar
          externalAccess:
            enabled: True
          podDisruptionBudget:
            enabled: True
          # User does NOT needs to provision the external database
          externalDatabase:
            enabled: false
```

### Version

17.0.0

### Expected behavior

I was expecting an instance of Keycloak would be deployed.

### Actual behavior

Nothing

### How to Reproduce?

1. Install OLM
2. Install Keycloak Operator CRDs
3. `kubectl apply` the following:
```
apiVersion: keycloak.org/v1alpha1
        kind: Keycloak
        metadata:
          name: example-keycloak
          namespace: "{{ namespace }}"
          labels:
            app: sso
        spec:
          instances: 1
          extensions:
            - https://github.com/aerogear/keycloak-metrics-spi/releases/download/1.0.4/keycloak-metrics-spi-1.0.4.jar
          externalAccess:
            enabled: True
          podDisruptionBudget:
            enabled: True
          # User does NOT needs to provision the external database
          externalDatabase:
            enabled: false
```
