### ISSUE TITLE
Implement Kubernetes recommended labels

### ISSUE THREAD

**Issue by hbjydev** [keycloak/keycloak-operator#529]
### Description

Given the following Keycloak resource:

```yml
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak-primary
  labels:
    app: keycloak-primary
spec:
  instances: 1
  externalAccess:
    enabled: true
```

The only label `keycloak-primary` will get is `app=keycloak-primary`. This is fine, it's a user-configured label. However, like [awx-operator](https://github.com/ansible/awx-operator), I feel this operator should _also_ add the standard [`app.kubernetes.io` labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/). These cannot _entirely_ be done by the user as far as I am aware, because certain labels (such as `app.kubernetes.io/component` and `app.kubernetes.io/name`) would be different depending on which resource is being labelled.

### Motivation

This ensures that all of the resources generated by `keycloak-operator` have a standard set of labels that can be used in some external tooling (like a custom dev platform, for example) to manage all of these without needing to try and manually investigate each resource the operator deploys.

### Details

For example, the `postgres` container this creates should be created with the following labels:

```yml
app.kubernetes.io/name: postgres
app.kubernetes.io/instance: keycloak-primary-postgres
app.kubernetes.io/version: <version of the postgres db deployed>
app.kubernetes.io/component: database
app.kubernetes.io/part-of: keycloak-primary
app.kubernetes.io/managed-by: keycloak-operator
app.kubernetes.io/created-by: keycloak-operator
app.kubernetes.io/operator-version: 17.0.0
```

See [awx-operator for example](https://github.com/ansible/awx-operator/blob/devel/roles/installer/tasks/main.yml#L2)
