### ISSUE TITLE
Invalid service when external database specified by ip

### ISSUE THREAD

**Issue by BcTpe4HbIu** [keycloak/keycloak-operator#536]
### Describe the bug

I'm trying to use KeyCloak with external database. But operator fails to create service for database with error `{"level":"info","ts":1650327911.7331116,"logger":"action_runner","msg":"(    4)     FAILED Update Postgresql KeycloakService : Service \"keycloak-postgresql\" is invalid: spec.clusterIPs[0]: Invalid value: []string(nil): primary clusterIP can not be unset"}`. And endpoints object not created at all.

### Version

17.0.1

### Expected behavior

Service created along with endpoints object.

### Actual behavior

Operator fails to create service for database with error `{"level":"info","ts":1650327911.7331116,"logger":"action_runner","msg":"(    4)     FAILED Update Postgresql KeycloakService : Service \"keycloak-postgresql\" is invalid: spec.clusterIPs[0]: Invalid value: []string(nil): primary clusterIP can not be unset"}`. And endpoints object not created at all.

### How to Reproduce?

kubernetes 1.20.4
operator quay.io/keycloak/keycloak-operator:17.0.1-legacy
```
---
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  labels:
    app: keycloak
  name: keycloak
spec:
  instances: 1
  externalAccess:
    enabled: false
  externalDatabase:
    enabled: true
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: supersecret
  POSTGRES_USERNAME: keycloak
  POSTGRES_DATABASE: keycloak
  POSTGRES_SUPERUSER: "false"
  POSTGRES_EXTERNAL_ADDRESS: 10.0.0.60
  POSTGRES_EXTERNAL_PORT: "5432"
```

**Comment by vmuzikar** [comment]
@BcTpe4HbIu Thank you for reporting this. Closing this as I believe it is a duplicate of #526. Feel free to reopen if you think otherwise.

**Comment by BcTpe4HbIu** [comment]
@vmuzikar Could you provide example manifests for Keycloak with external database?
Only way I've managed to make it work is by using experimental:

```yaml
experimental:
      env:
        - name: DB_ADDR
          valueFrom:
            secretKeyRef:
              name: keycloak-db-secret
              key: POSTGRES_HOST 
```
