### ISSUE TITLE
where is the realm with ldap documentation?

### ISSUE THREAD

**Issue by mjschmidt** [keycloak/keycloak-operator#560]
### Description

Just wondering in the userFederationProciders area for a real crd if there are docs to all the possible config elements?

I am trying to create a realm with ldap and I see ad is the option for active directory, but I am wondering how to create a realm that is backed  by a generic ldap (so option other instead of ad). Is this option "o" or "other" tried several things but can't seem to guess the correct config.

The example I am looking at is here:
https://github.com/keycloak/keycloak-operator/blob/main/deploy/examples/realm/realm_with_ldap.yaml

### Discussion

n/a

### Motivation

none if documentation exists

### Details

no further details

**Comment by mjschmidt** [comment]
This is the closest thing I've been able to find thus far, but it only has a definition no options listed:
https://www.keycloak.org/docs-api/10.0/rest-api/index.html#_definitions

**Comment by tadamo** [comment]
I don't have a complete example, but I'm currently trying to get this figured out myself. I think you're looking for what value to put in `vendor`, correct? Should be `rhds`.

```
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: ldap
  namespace: keycloak
  labels:
    app: ldap
spec:
  instanceSelector:
    matchLabels:
      app: sso
  realm:
    id: ldap
    realm: ldap
    enabled: true
    displayName: "ldap realm"
    userFederationProviders:
      - displayName: ldap
        providerName: ldap
        config:
          priority: "0"
          editMode: "READ_ONLY"
          syncRegistrations: "false"
          vendor: "rhds"
          usernameLDAPAttribute: "uid"
          rdnLDAPAttribute: "uid"
          uuidLDAPAttribute: "uid"
```

I had to manually set this up in the UI and then look at the API response to determine the values.
