### ISSUE TITLE
Suspected ERROR on keycloak service target port

### ISSUE THREAD

**Issue by JiyeYu** [keycloak/keycloak-operator#99]
## Description
$ kubectl describe service keycloak -n keycloak
Type:              ClusterIP
IP:                10.108.62.181
Port:              keycloak  8443/TCP
TargetPort:        8443/TCP
Endpoints:         172.17.0.4:8443

while keycloak pod ip is using port 8080:
```
livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /auth/realms/master
        port: 8080
        scheme: HTTP
```

Due to this error, we cannot visit keycloak page through ingress.

Either fix the keycloak pod port or change the target port of keycloak service will fix this error.
